<ol class="breadcrumb">
	<li class="active">Lista maszyn wirtualnych</li>
</ol>

<?php if (isset($agenterror)): ?>
	<div class="alert alert-danger">
		Brak połaczenia z nadzorcą maszyn wirtualnych.
	</div>
<?php else: ?>
	<div class="panel panel-default">
		<div class="panel-body">
			<?php if (count($domains) == 0): ?>
				<div class="alert alert-danger">
					Brak maszyn wirtualnych
				</div>
			<?php else: ?>
				<table class="table table-hover vmlist">
					<thead>
						<th class="id">
							#
						</th>
						<th class="name">
							Nazwa maszyny wirtualnej
						</th>
						<th class="status">
							Status
						</th>
						<th class="actions">
							Akcje
						</th>
						<th class="vnc">
							VNC
						</th>
						<th class="temporaryvnc">
							Tymczasowe hasło VNC
						</th>
					</thead>
					<?php $i = 1; ?>
					<tbody>
						<?php foreach ($domains as $domain): ?>
							<tr class="trmouse" data-domainname="<?php echo $domain -> getName(); ?>">
								<td class="domaineditclick" data-domainname="<?php echo $domain -> name; ?>">
									<?php echo $i++; ?>
								</td>
								<td class="domaineditclick" data-domainname="<?php echo $domain -> name; ?>">
									<?php echo $domain -> getName(); ?>
								</td>
								<td class="domaineditclick" data-domainname="<?php echo $domain -> name; ?>">
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_NOSTATE): ?>
										<span class="text-danger">nieznany</span>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTOFF): ?>
										<span class="text-danger">wyłączona</span>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTDOWN): ?>
										<span class="text-warning">w trakcie wyłączania</span>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_RUNNING): ?>
										<span class="text-success">uruchomiona</span>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_PAUSED): ?>
										<span class="text-warning">wstrzymana</span>
									<?php endif; ?>
								</td>
								<td>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTOFF): ?>
										<a href="<?php echo $this -> url('domain', array(
												'controller' => 'domain', 
												'action' => 'start',
												'name' => $domain -> getName())); ?>" class="btn btn-success btn-xs" title="Uruchom maszynę">
											<span class="glyphicon glyphicon-play"></span>
										</a>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_RUNNING): ?>
										<a href="<?php echo $this -> url('domain', array(
												'controller' => 'domain', 
												'action' => 'destroy',
												'name' => $domain -> getName())); ?>" class="btn btn-danger btn-xs" title="Zatrzymaj maszynę">
											<span class="glyphicon glyphicon-stop"></span>
										</a>
										<a href="<?php echo $this -> url('domain', array(
												'controller' => 'domain', 
												'action' => 'suspend',
												'name' => $domain -> getName())); ?>" class="btn btn-warning btn-xs" title="Wstrzymaj maszynę">
											<span class="glyphicon glyphicon-pause"></span>
										</a>
										<a href="<?php echo $this -> url('domain', array(
												'controller' => 'domain', 
												'action' => 'reset',
												'name' => $domain -> getName())); ?>" class="btn btn-danger btn-xs" title="Zresetuj maszynę">
											<span class="glyphicon glyphicon-refresh"></span>
										</a>
									<?php endif; ?>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_PAUSED): ?>
										<a href="<?php echo $this -> url('domain', array(
												'controller' => 'domain', 
												'action' => 'resume',
												'name' => $domain -> getName())); ?>" class="btn btn-success btn-xs" title="Wznów maszynę">
											<span class="glyphicon glyphicon-play"></span>
										</a>
									<?php endif; ?>
								</td>
								<td>
									<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_RUNNING): ?>
										<?php $options = $domain -> getGraphicConsoleOptions(); ?>
										<?php echo $domain -> getAgent() -> getExternalAddress(); ?>
										: <?php echo $options['port']; ?>
									<?php endif; ?>
								</td>
								<td>
									<?php $passwd = $domain -> getTemporaryPassword(); ?>
									<?php if ($passwd == ''): ?>
										<span class="text-muted"> - </span>
									<?php else: ?>
										<span style="display: none;" class="plaintextpassword<?php echo $i; ?>"><?php echo $passwd; ?></span>
										<a href="#" class="showpass showpass<?php echo $i; ?>" data-id="<?php echo $i; ?>">Pokaż hasło</a>	
										<a style="display: none;" href="#" class="hidepass hidepass<?php echo $i; ?>" data-id="<?php echo $i; ?>">Ukryj hasło</a>
									<?php endif; ?>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			<?php endif; ?>
		</div>
	</div>
	
	<script type="text/javascript">
		$('.showpass').click(function(event){
			event.preventDefault();
			$('.plaintextpassword' + $(this).attr('data-id')).show();
			$('.showpass' + $(this).attr('data-id')).hide();
			$('.hidepass' + $(this).attr('data-id')).show();
		});
		$('.hidepass').click(function(event){
			$('.plaintextpassword' + $(this).attr('data-id')).hide();
			$('.showpass' + $(this).attr('data-id')).show();
			$('.hidepass' + $(this).attr('data-id')).hide();
		})
		$('.domaineditclick').click(function(event){
			location.href = '<?php echo $this -> url('domain', array(
				'controller' => 'domain', 
				'action' => 'details')); ?>/' + $(this).attr('data-domainname');
		});
		$('.btn').tooltip();
	</script>
<?php endif; ?>
