#!/usr/bin/env python2
# -*- encoding: utf-8

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# Ustawianie katalogu aplikacji
import os
import sys

# Zmiana katalogu działania aplikacji
path = os.path.abspath(os.path.dirname(sys.argv[0]))
libpath = os.path.abspath(path + "/../lib/")
os.chdir(libpath)
sys.path.append(libpath)

import time
import json

from folavirt.disks.discover.LookupBaseByAvahi import LookupBaseByAvahi
from folavirt.disks.discover.LookupSnapshotsByAvahi import LookupSnapshotsByAvahi

# Szukanie baz
baselookup = LookupBaseByAvahi()
time.sleep(1)
bases = baselookup.getBase()
baselookup.kill()

# Szukanie snapshotów
snapshotslookup = LookupSnapshotsByAvahi()
time.sleep(1)
snapshots = snapshotslookup.getSnapshots()
snapshotslookup.kill()

# Tworzenie obiektu w formacie json
result = {'base' : bases, 'snapshot' : snapshots}
print json.dumps(result)
