<div class="panel panel-default">
	<div class="panel-heading">
		<span class="glyphicon glyphicon-th"></span> Szczegóły agenta
	</div>
	<div class="panel-body">
		<dl class="dl-horizontal">
			<dt>
				Nazwa
			</dt>
			<dd>
				<?php echo $agent -> getName(); ?>
			</dd>
			<dt>
				Adres
			</dt>
			<dd>
				<?php echo $agent -> getAddress(); ?>
			</dd>
			<dt>
				Port
			</dt>
			<dd>
				<?php echo $agent -> getPort(); ?>
			</dd>
			<dt>
				Stan
			</dt>
			<dd>
				<?php try{ ?>
					<?php if ($agent -> alive()): ?>
						<span class="text-success">działa</span>
					<?php else: ?>
						<span class="text-danger">nie działa</span>
					<?php endif; ?>
				<?php } catch (Exception $e) { ?>
					<span class="text-danger">nie działa</span>
				<?php } ?>
			</dd>
		</dl>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<span class="glyphicon glyphicon-file"></span> Pule dyskowe
	</div>
	<div class="panel-body">
		<table class="table table-hover">
			<thead>
			 	<th>
					# 		
			 	</th>
			 	<th>
			 		Nazwa
			 	</th>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php foreach ($agent -> getPools() as $pool): ?>
				 	<tr class="pooldetailslink trmouse" data-pool="<?php echo $pool; ?>">
				 		<td>
				 			<?php echo $i++; ?>
				 		</td>
				 		<td>
				 			<?php echo $pool; ?>
				 		</td>
				 	</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$('.pooldetailslink').click(function(event){
		location.href = '/panel/admin/hosts/pool/<?php echo $id; ?>/' + $(this).attr('data-pool');
	});
</script>
