<div class="panel panel-default">
	<div class="panel-heading">
		Akcje
	</div>
	<div class="panel-body">
		<a class="btn btn-primary iscsiupdate" href="<?php echo $this -> url('hosts', array('controller' => 'hosts', 'action' => 'iscsiupdate')); ?>">
			<span class="glyphicon glyphicon-refresh"></span> <span class="iscsiupdatetext">Synchronizuj pule iSCSI</span>
		</a>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<span class="glyphicon glyphicon-th"></span> Lista hostów
	</div>
	<div class="panel-body">
		<table class="table table-hover">
			<thead>
				<th>
					#
				</th>
				<th>
					Nazwa
				</th>
				<th>
					Adres IP
				</th>
				<th>
					Port
				</th>
				<th>
					Stan
				</th>
			</thead>
			<tbody>
				<?php $i = 0; ?>
				<?php foreach ($agents as $agent): ?>
					<tr class="hostdetialslink trmouse" data-id="<?php echo ++$i; ?>">
						<td>
							<?php echo $i; ?>
						</td>
						<td>
							<?php echo $agent -> getName(); ?>
						</td>
						<td>
							<?php echo $agent -> getAddress(); ?>
						</td>
						<td>
							<?php echo $agent -> getPort(); ?>
						</td>
						<td>
							<?php try{ ?>
								<?php if ($agent -> alive()): ?>
									<span class="text-success">działa</span>
								<?php else: ?>
									<span class="text-danger">nie działa</span>
								<?php endif; ?>
							<?php } catch (Exception $e) { ?>
								<span class="text-danger">nie działa</span>
							<?php } ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$('.hostdetialslink').click(function(event){
		location.href = '/panel/admin/hosts/details/' + $(this).attr('data-id');
	});
	$('.iscsiupdate').click(function(event){
		$('.iscsiupdate').removeClass('btn-primary');
		$('.iscsiupdate').addClass('btn-success');
		$('.iscsiupdatetext').html('Oświeżanie...');
	});
</script>
