<div class="panel panel-default">
	<div class="panel-heading">
		Lista maszyn wirtualnych
	</div>
	<div class="panel-body">
		<table class="table table-hover">
			<thead>
				<th>
					#
				</th>
				<th>
					Nazwa
				</th>
				<th>
					Host
				</th>
				<th>
					Stan
				</th>
				<th></th>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php foreach ($domains as $domain): ?>
					<tr class="domaineditclick trmouse" data-domainname="<?php echo $domain -> getName(); ?>">
						<td>
							<?php echo $i++; ?>
						</td>
						<td>
							<?php echo $domain -> getAgent() -> getName(); ?>
						</td>
						<td>
							<?php echo $domain -> getName(); ?>
						</td>
						<td>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_NOSTATE): ?>
								<span class="text-danger">nieznany</span>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTOFF): ?>
								<span class="text-danger">wyłączona</span>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTDOWN): ?>
								<span class="text-warning">w trakcie wyłączania</span>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_RUNNING): ?>
								<span class="text-success">uruchomiona</span>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_PAUSED): ?>
								<span class="text-warning">wstrzymana</span>
							<?php endif; ?>
						</td>
						<td>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_SHUTOFF): ?>
								<a href="<?php echo $this -> url('domain', array(
										'controller' => 'domain', 
										'action' => 'start',
										'name' => $domain -> getName())); ?>?back=alldomains" class="btn btn-success btn-xs" title="Uruchom maszynę">
									<span class="glyphicon glyphicon-play"></span>
								</a>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_RUNNING): ?>
								<a href="<?php echo $this -> url('domain', array(
										'controller' => 'domain', 
										'action' => 'destroy',
										'name' => $domain -> getName())); ?>?back=alldomains" class="btn btn-danger btn-xs" title="Zatrzymaj maszynę">
									<span class="glyphicon glyphicon-stop"></span>
								</a>
								<a href="<?php echo $this -> url('domain', array(
										'controller' => 'domain', 
										'action' => 'suspend',
										'name' => $domain -> getName())); ?>?back=alldomains" class="btn btn-warning btn-xs" title="Wstrzymaj maszynę">
									<span class="glyphicon glyphicon-pause"></span>
								</a>
								<a href="<?php echo $this -> url('domain', array(
										'controller' => 'domain', 
										'action' => 'reset',
										'name' => $domain -> getName())); ?>?back=alldomains" class="btn btn-danger btn-xs" title="Zresetuj maszynę">
									<span class="glyphicon glyphicon-refresh"></span>
								</a>
							<?php endif; ?>
							<?php if ($domain -> getState() == \Application\Model\Folavirt\Remote\Domain::DOMAIN_PAUSED): ?>
								<a href="<?php echo $this -> url('domain', array(
										'controller' => 'domain', 
										'action' => 'resume',
										'name' => $domain -> getName())); ?>?back=alldomains" class="btn btn-success btn-xs" title="Wznów maszynę">
									<span class="glyphicon glyphicon-play"></span>
								</a>
							<?php endif; ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
	$('.domaineditclick').click(function(event){
		location.href = '<?php echo $this -> url('domain', array(
			'controller' => 'domain', 
			'action' => 'details')); ?>/' + $(this).attr('data-domainname');
	});
</script>