<div class="panel panel-default">
	<div class="panel-heading">
		Pula dyskowa
	</div>
	<div class="panel-body">
		<dl class="dl-horizontal">
			<dt>
				Nazwa
			</dt>
			<dd>
				<?php echo $pool -> getName(); ?>
			</dd>
			<dt>
				Agent
			</dt>
			<dd>
				<?php echo $pool -> getAgent() -> getName(); ?>
			</dd>
		</dl>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		Lista woluminów
	</div>
	<div class="panel-body">
		<table class="table table-hover">
			<thead>
				<th>
					#
				</th>
				<th>
					Nazwa
				</th>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php foreach ($pool -> getVolumes() as $volume): ?>
					<tr>
						<td>
							<?php echo $i++; ?>
						</td>
						<td>
							<?php echo $volume; ?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
